name: LyttleTokens
version: '${projectVersion}'
main: com.lyttldev.lyttletokens.LyttleTokens
api-version: '1.21'
depend: [Vault, LyttleScoreboardEconomy]
commands:
  lyttletokens:
    usage: /lyttletokens [reload]
    description: Shows plugin version and reload config files
    permission: lyttletokens.staff